[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200

[build.environment]
  NODE_VERSION = "20"

# If using Netlify Edge Functions for better performance
[functions]
  node_bundler = "esbuild"

